config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :addresses, only: [:create, :destroy, :update, :edit, :new]
  resources :bank_accounts, only: [:create, :destroy, :update, :edit, :new]
  resources :pictures

  devise_for :administrators
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks" }

  authenticated :admin do
    root to: 'users#index'
  end

  authenticated :user do
    root to: 'listings#index'
  end
  
  resources :listings do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :users do
    resources :comments, only: [:new, :create, :destroy]
  end

=begin
  # Usuarios admin Ya está hecho
  get "admins/users/new" => 'users#new', as: 'add_user_admin'
  post "admins/users/new" => 'users#create', as: 'login_admin_user'
  get "admins/users/:id/edit" => "users#edit", as: "edit_user_adm"
  patch "admins/users/:id" => 'users#update', as: 'edit_user_admin'
  delete "admins/users/:id" => 'users#destroy', as: 'destroy_user_admin'
  get "admins/users" => 'users#index', as: 'list_user_admin'

  #subjects admin Ya está hecho
  get "admins/subjects" => 'subjects#index', as: 'subjects'
  post "admins/subjects" =>  'subjects#create'
  get "admins/subjects/new" => "subjects#new", as:'new_subject'                             
  get "admins/subjects/:id/edit" => "subjects#edit", as: "edit_subject" 
  get "admins/subjects/:id" => "subjects#show", as:"subject"
  patch "admins/subjects/:id" => "subjects#update"
  put "admins/subjects/:id" => "subjects#update"
  delete "admins/subjects/:id" => "subjects#destroy"

  #categorias admin Ya está hecho
  get "admins/categories" => 'categories#index', as: 'categories'
  post "admins/categories" =>  'categories#create'
  get "admins/categories/new" => "categories#new", as:'new_category'                             
  get "admins/categories/:id/edit" => "categories#edit", as: "edit_category" 
  get "admins/categories/:id" => "categories#show", as:"category"
  patch "admins/categories/:id" => "categories#update"
  put "admins/categories/:id" => "categories#update"
  delete "admins/categories/:id" => "categories#destroy"

  #artwork admin
  get "admins/artworks" => 'listings#index_admin', as: 'artworks_list'
  post "admins/artworks/new" =>  'listings#create_admin'
  get "admins/artworks/new" => "listings#new_admin", as:'new_listing_admin'                             
  get "admins/artworks/:id/edit" => "listings#edit_admin", as: "edit_listing_admin" 
  patch "admins/artworks/:id" => "listings#update_admin", as: "update_listing_admin"
  put "admins/artworks/:id" => "listings#update_admin"
  delete "admins/artworks/:id" => "listings#destroy_admin", as:"destroy_listing_admin"

  #addresses admin
  get "admins/addresses" => 'addresses#index_admin', as: 'addresses_list'
  post "admins/addresses/new" =>  'addresses#create_admin', as:'create_address_admin'
  get "admins/addresses/new" => "addresses#new_admin", as:'new_address_admin'                             
  get "admins/addresses/:id/edit" => "addresses#edit_admin", as: "edit_address_admin" 
  patch "admins/addresses/:id" => "addresses#update_admin", as: "update_address_admin"
  put "admins/addresses/:id" => "addresses#update_admin"
  delete "admins/addresses/:id" => "addresses#destroy_admin", as:"destroy_address_admin"

  #bank accounts_admin
  get "admins/bank_accounts" => 'bank_accounts#index_admin', as: 'bank_accounts_list'
  post "admins/bank_accounts/new" =>  'bank_accounts#create_admin', as: 'create_bank_account_admin'
  get "admins/bank_accounts/new" => "bank_accounts#new_admin", as:'new_bank_account_admin'                             
  get "admins/bank_accounts/:id/edit" => "bank_accounts#edit_admin", as: "edit_bank_account_admin" 
  patch "admins/bank_accounts/:id" => "bank_accounts#update_admin", as: "update_bank_account_admin"
  put "admins/bank_accounts/:id" => "bank_accounts#update_admin"
  delete "admins/bank_accounts/:id" => "bank_accounts#destroy_admin", as:"destroy_bank_account_admin"
=end

  match '/admin/administrators' => redirect('/admin/users'), via: [:get]
  match '/admin/signin' =>redirect('administrators/sign_in'), via: [:get]
  get "/vacio" => "templates#vacio", as: "edit_admin_administrator"

  Tolaria.draw_routes(self)

  #AJAX
  get "/fetch_listings" => 'listings#from_category', as: 'fetch_listings'
  get "/fetch_subjects" => 'listings#subjects', as: 'fetch_subjects'
  get "/fetch_comments_listing" => 'listings#comments', as: 'fetch_comments_listing'
  get "/fetch_listings_user" => 'users#listings', as: 'fetch_listings_user'
  get "/fetch_comments_user" => 'users#comments', as: 'fetch_comments_user'

  get '/pages/styles'
  get '/pages/appreciation'
  get '/pages/exhibition'
  get '/pages/artist'
  get '/pages/top_artist'
  get '/pages/museums'
  get '/pages/art_appreciation'
  get '/pages/about_us'
  get '/contact', to: 'messages#new', as: 'pages_contact'
  get "/curated" => 'listings#curated', as:"listings_curated"
  get '/listings' => 'listings#index', defaults: { format: 'js' }
  get "/elearning" => 'pages#elearning', as:"pages_elearning"
  get "/about" => 'pages#about', as:"pages_about"
  get '/seller' => "listings#seller"
  get '/sales' => "orders#sales"
  get '/purchases' => "orders#purchases"
  get "/search" => "pages#search", as:"search"
  get '/:nick' => 'users#show', as:"user_profile"
  get "/add/:listing_id", as: :add_to_cart, to: "in_shopping_carts#create"
  get "/price/:range" => 'listings#from_price', as:'range_price'
  get "/pages_category/:category/" => 'pages#pages_category', as: 'pages_category'
  get "/pages_subject/:subject/" => 'pages#pages_subject', as: 'pages_subject'
  get "/bysubject/:subject" => 'listings#from_subject', as: 'from_subject'

  post '/contact', to: 'messages#create'

  root 'listings#index'
  
end

app/models/listing.rb
class Listing < ActiveRecord::Base

  validates :name, :description, presence: true
  
  belongs_to :user
  belongs_to :category
  belongs_to :subject

  has_many :comments, :dependent => :destroy
  has_many :pictures, :dependent => :destroy

	manage_with_tolaria using: {
		icon: "image",
		category: "Content administration",
		priority: 1,
		permit_params: [
			:name,
			:description,
			:price,
			:public,
			:user_id,
			:category_id,
			:subject_id,
            :picture_ids => []
		]
	}

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy, :edit_admin, :update_admin, :destroy_admin]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  before_action :check_payment, only: [:new]

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  def index
    @title = "LatamArt - Home"
    Listing.connection.execute "select setseed(0.#{(request.ip.to_s.split('.').last.to_i + Date.today.wday.to_i).to_s})"
    @listings = Listing.joins(:user).where(:listings => {:public => true},:users => {:public => true}).order("random()").page(params[:page]).per(12)
    client = Mysql2::Client.new(:host => "latampostdbmysql.cw9xqocyq7hv.us-east-1.rds.amazonaws.com", :database => "latinamericanpost_db", :username => "latampost_user", :password => "?#22HrD,BqoG")
    @articles = client.query("SELECT latinamericanpost_db.fx2su_content.`id` AS `id`, latinamericanpost_db.fx2su_content.`title` AS `title`, `images`, `introtext`, `fulltext`, latinamericanpost_db.fx2su_categories.`alias` AS `category`, `created`, `created_by`, `state`, latinamericanpost_db.fx2su_content.`metadesc` AS `metadesc`, latinamericanpost_db.fx2su_content.`metakey` AS `metakey`, latinamericanpost_db.fx2su_content.`hits` AS `hits`, `publish_up`, latinamericanpost_db.fx2su_content.`language` AS `language`, latinamericanpost_db.fx2su_content.`alias` AS `alias` 
      FROM latinamericanpost_db.fx2su_content
      INNER JOIN latinamericanpost_db.fx2su_categories ON latinamericanpost_db.fx2su_content.catid = latinamericanpost_db.fx2su_categories.id
      WHERE catid in (194,301,223) and state = 1 order by id asc;")
    client.close
    respond_to do |format|
      format.html
      format.js
    end
  end

  def curated
    @title = "LatamArt - Staff picks"
    Listing.connection.execute "select setseed(0.#{(request.ip.to_s.split('.').last.to_i + Date.today.wday.to_i).to_s})"
    @listings = Listing.joins(:user).where(:users => {:statePayment => true, :public => true}, :listings => {:public => true}).order('random()').page(params[:page]).per(9)
    client = Mysql2::Client.new(:host => "latampostdbmysql.cw9xqocyq7hv.us-east-1.rds.amazonaws.com", :database => "latinamericanpost_db", :username => "latampost_user", :password => "?#22HrD,BqoG")
    @articles = client.query("SELECT latinamericanpost_db.fx2su_content.`id` AS `id`, latinamericanpost_db.fx2su_content.`title` AS `title`, `images`, `introtext`, `fulltext`, latinamericanpost_db.fx2su_categories.`alias` AS `category`, `created`, `created_by`, `state`, latinamericanpost_db.fx2su_content.`metadesc` AS `metadesc`, latinamericanpost_db.fx2su_content.`metakey` AS `metakey`, latinamericanpost_db.fx2su_content.`hits` AS `hits`, `publish_up`, latinamericanpost_db.fx2su_content.`language` AS `language`, latinamericanpost_db.fx2su_content.`alias` AS `alias` 
      FROM latinamericanpost_db.fx2su_content
      INNER JOIN latinamericanpost_db.fx2su_categories ON latinamericanpost_db.fx2su_content.catid = latinamericanpost_db.fx2su_categories.id
      WHERE catid in (194,301,223) and state = 1 order by id asc;")
    client.close
    respond_to do |format|
      format.html
      format.js
    end
  end


  def subjects
    @selected = Subject.all.order("random()").page(params[:page]).per(6)

    respond_to do |format|
        format.js
    end
  end

  # Función para dividirlo en categorías
  def from_category

    if params[:cat_id] == "1"
      @selected = Listing.all.order("random()").page(params[:page]).per(8)
    else
      @selected = Listing.where(:category_id => params[:cat_id]).order(created_at: :desc).page(params[:page]).per(8)
    end 

    respond_to do |format|
        format.js
    end
  end

  # Función para dividirlo por precio
  def from_price
    minimium = Listing.all.minimum(:price)
    maximum = Listing.all.maximum(:price)
    range = ((maximum-minimium)/3).ceil

    if params[:range] == "range_price_1"
      @listings = Listing.where('price BETWEEN ? AND ?', minimium, minimium+range).page(params[:page]).per(12)
    elsif params[:range] == "range_price_2"
      @listings = Listing.where('price BETWEEN ? AND ?', minimium+range, minimium+(range*2)).page(params[:page]).per(12)
    elsif params[:range] == "range_price_3"
      @listings = Listing.where('price BETWEEN ? AND ?', minimium+(range*2), minimium+(range*3)).page(params[:page]).per(12)
    end 
  end 

  #Función para dividirlo por categorías
  def from_subject
    @listings = Listing.where('subject_id = ?', params[:subject]).order(:name).page(params[:page]).per(6)
  end

  #Función para la paginación de los comentarios
  def comments
    @selected = Comment.where("listing_id = ?", params[:listing_id]).order(created_at: :desc).page(params[:page]).per(9)

    respond_to do |format|
        format.js
    end

  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @comment = Comment.new
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit 
  end

  # POST /listings
  # POST /listings.json
  def create

    @listing = current_user.listings.new(listing_params)
    @listing.pictures << Picture.find(params[:photos].split(","))

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update

    @listing.pictures << Picture.find(params[:photos].split(","))
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :quantity, :category_id, :subject_id, :currency_id)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end

    # Use callbacks to prevent to add new artworks if payment is not present
    def check_payment
      if current_user.statePayment == false && current_user.listings.count >= 3
        redirect_to root_url, alert: "Sorry, you must contact to administrator to accomplish a payment, you have a maximum of 3 artworks"
      end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_comment_grid.html.erb
<div>
  <div id="comments_grid" >
    <%= render partial: 'comments_list', locals: {comments: comments}  %>
  </div>
</div>

app/views/listings/_listing.html.erb
<% if (controller_name == "listings" && action_name == "index") %>
	<% if listing.pictures[0].present?%>
		<%= link_to listing do %>
		<figure class="imghvr-push-up border-image">
			<%= image_tag(listing.pictures[0].image.url(:medium), class: "main-image") %>
			<% if listing.user.statePayment == true %>
				<%= image_tag('star.png', size:"30x30", class: "star-image") %>
			<% end %>
		    <figcaption class="<%= (listing.user.statePayment ? 'gold' : '')%>">
	        	<h6><b><%=listing.name%></b></h6>
	        	<h6>By <%=listing.user.first_name + ' ' + listing.user.last_name%></h6>
	      	</figcaption>
		</figure>
		<% end %>
	<% end %>
<% else %>
	<div class="col-xs-4">
		<% if listing.pictures[0].present?%>
			<%= link_to listing do %>
				<%= image_tag(listing.pictures[0].image.url(:categories))%>
				<% if listing.user.statePayment == true %>
					<%= image_tag('star.png', size:"30x30", class: "star-image") %>
				<% end %>
			<% end %>
		<% end %>
		<div class="row text-center">
			<p class="title"><%=listing.name%></p>
			<p class="description"><%= (listing.description.downcase == "n/a") ? "" :  listing.description.truncate(110) %></p>
		</div>
	</div>
<% end %>

app/views/listings/_subjects_list.html.erb
<div class="container">
    <div class="row">


        <% subjects.each do |subject|%>
            <div class="col-sm-5 col-md-pull">
             
                <% if subject.image.present? %>
                   
                    <%= link_to from_subject_path(:subject => subject.id), class: "box-content" do%>
                        <%= image_tag(subject.image.url(:categories), class: "full_column")  %>
                        <span class="texto" ><%= subject.name%></h4>
                    <% end %>
                <% else %>
                    <%= link_to from_subject_path(:subject => subject.id), class: "box-content" do%>
                        <%= image_tag("slide1.jpg", class: "full_column") %>
                        
                        <span class="texto" ><%= subject.name%></h4>
                    <% end %>
                <% end %>
            </div>
        <% end %>
        



    </div>
</div>
<div class="container">
    <div class='row text-center'>
    	<%= paginate subjects %>
    </div>
</div>

<script type="text/javascript">
$.fn.ajaxPagination = function() {
  this.on("click", function () {
    $.get(this.href, null, null, "script");
    return false;
  });
}

$(document).ready(function() {
  $( ".pagination a" ).ajaxPagination();
})
</script>

app/views/listings/comments.js.erb
$("#comments_grid").html("<%= escape_javascript(render partial: 'comments_list', locals: { comments: @selected } ) %>"); 
$(".pagination a").ajaxPagination();

app/views/listings/curated.js.erb
$('#my-listings').append('<%= j render @listings %>');
$('.paginator').hide();
<% if @listings.next_page %>
	$('.pagination').replaceWith('<%= j paginate @listings %>');
<% else %>
	$(window).off('scroll');
	$('.pagination').remove();
<% end %>
<% sleep 2 %>

app/views/listings/from_category.js.erb
$("#items_grid").html("<%= escape_javascript(render partial: 'items_list', locals: { listings: @selected } ) %>"); 
$(".pagination a").ajaxPagination();

app/views/listings/from_price.html.erb
<%minimium = Listing.all.minimum(:price)%>
<%maximum = Listing.all.maximum(:price)%>
<%range = ((maximum-minimium)/3).ceil%>
<%current = ""%>

<% if params[:range] == "range_price_1" %>
	<% current = number_to_currency(minimium.to_s) + ' and ' + number_to_currency((minimium+range).to_s) %>
<% elsif params[:range] == "range_price_2" %>
	<% current = number_to_currency((minimium+range).to_s) + ' and ' + number_to_currency((minimium+(range*2))).to_s %>
<% elsif params[:range] == "range_price_3" %>
	<% current = number_to_currency((minimium+(range*2))).to_s + ' and ' + number_to_currency((minimium+(range*3))).to_s %>
<% end %>

<div class="row">
	<div class="gallery col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<h1 class="gallery-title">Artworks</h1>
	</div>

	<% @listings.each do |item| %>
	  <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter all">
	    <%= link_to item do %>
	    	<%=image_tag(item.pictures[0].image.url(:categories), class: "img-responsive")%>

		    
		<% end %>
	  </div>
	<% end %>
</div>

<div class='row text-center'>
	<%= paginate @listings %>
</div>

app/views/listings/index_admin.html.erb
<%= render 'shared_admin/menu' %>
<div class = "col-md-10 text-center">

  <h4>Artworks</h4>

  <table class="table table-striped table-bordered">
    <tr>
      <th class="center">Name</th>
      <th class="center">Stock</th>
      <th class="center">Artist</th>
      <th class="center">Image</th>
      <th colspan="2"></th>
    </tr>

    <% @listings.each do |listing| %>
      <tr>
        <td class="center"><%= listing.name%>
        <td class="center"><%= listing.quantity %></td>
        <td class="center"><%= listing.user.first_name + ' ' + listing.user.last_name %></td>
        <td class="center"><%= image_tag(listing.pictures[0].image.url(:thumb))%></td>
        <td class="center"><%= link_to 'Edit', edit_listing_admin_path(listing) %></td>
        <td class="center"><%= link_to 'Destroy', destroy_listing_admin_path(listing), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <br>

  <%= link_to 'New artwork', new_listing_admin_path %>
</div>

app/views/listings/new.html.erb
<h1>Nueva obra</h1>

<%= render 'form' %>
<%= csrf_meta_tags %>

<%= link_to 'Regresar', listings_path, class: "btn btn-link" %>

app/views/listings/seller.html.erb
<br><br>
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Imagen</th>
    <th class="center">Nombre</th>
    <th class="center">Descripción</th>
    <th class="center">Acción</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td>
        <%= image_tag listing.pictures[0].image.url(:thumb) %>
      </td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'Nueva obra', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="row">
          <div class="gallery col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h1 class="gallery-title"><%= @listing.name %></h1>
          </div> 
          <div class="row">
           <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
              <% counter = 0 %>
              <% @listing.pictures.each do |picture|%>
                <% if counter == 0 %>
                  <div class="active item" data-slide-number="<%=counter%>">
                    <%= image_tag(picture.image.url(:large),class: "img-responsive", class: "full_column")%>    
                  </div>
                <% else %>
                  <div class="item" data-slide-number="<%=counter%>">
                    <%= image_tag(picture.image.url(:large),class: "img-responsive", class: "full_column")%>
                  </div>
                <% end %>
                <% counter = counter + 1%>
              <% end %>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <p><strong>Description: </strong><%= @listing.description %></p>
              <% if @listing.user.nick.present? %>
                <%=link_to user_profile_path(@listing.user.nick) do %>
                  <%= image_tag(@listing.user.photo.url(:thumb), size:"50x50")%>
                  <%= @listing.user.first_name + ' ' + @listing.user.last_name %>
                <% end %>
              <% else %>
                <div>
                  <%= image_tag(@listing.user.photo.url(:thumb), size:"50x50")%>
                  <%= @listing.user.first_name + ' ' + @listing.user.last_name %>
                </div>
              <% end %>
              <br>
              <br>
              <% if @listing.category.photo.present? %>
                <%= link_to pages_category_path(@listing.category.name.downcase) do %>
                  <%=image_tag(@listing.category.photo.url(:thumb), size:"50x50")%>
                  <%= @listing.category.name %>
                <% end %>
              <% else %>
                <%= link_to pages_category_path(@listing.category.name.downcase) do %>
                  <%= @listing.category.name %>
                <% end %>
              <% end %>
              <br>
              <br>
              <% if @listing.subject.image.present? %>
                <%= link_to from_subject_path(@listing.subject.id) do%>
                  <%=image_tag(@listing.subject.image.url(:thumb), size:"50x50")%>
                  <%= @listing.subject.name %>
                <% end %>
              <% else %>
                <%= link_to from_subject_path(@listing.subject.id) do%>
                  <%= @listing.subject.name %>
                <% end %>      
              <% end %>
              <br>
              <br>
              <% if @listing.comments.count == 0%>
                <strong> This artwork doesn't have comments yet </strong>
              <% else %>
                <p><strong>Global score: </strong><%= @listing.comments.average(:qualification).round(1).to_s + '/5.0'%></p>
              <% end %>
            </div>
          <% if current_user == @listing.user %>
            <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
          <% end %>
        </div>

        <% if @listing.user.statePayment == true %>
          <% if user_signed_in? %>  
            <div class="row">
              <%= render "comments/form-artwork" %>
            </div>
          <% end %>
        
          <div class="row">
            <h4>Comments</h4>
            <% if @listing.comments.count == 0 %>
              <strong>There are no comments for this artwork</strong>
            <% else %>
              <% @comments = @listing.comments.page(params[:page]).per(9)%>
              <%= render partial: 'comment_grid', locals: { comments: @comments} %>
            <% end %>
          </div>
          <br>
          <br>
        <% end %>

      </div>
    </div>
  </div>
</div> 
<br>
<br>
<br>
</div>


<script type="text/javascript">

    $(document).ready(function(){
        $.ajax({
         url: "/fetch_comments_listing",
         type: "GET",
         data: {listing_id: <%=@listing.id%>}
        });
    });

</script>

<script>
  jQuery(document).ready(function($) {
 
        $('#myCarousel').carousel({
                interval: 5000
        });
 
        $('#carousel-text').html($('#slide-content-0').html());
 
        //Handles the carousel thumbnails
        $('[id^=carousel-selector-]').click( function(){
                var id_selector = $(this).attr("id");
                var id = id_selector.substr(id_selector.length -1);
                var id = parseInt(id);
                $('#myCarousel').carousel(id);
        });
 
 
        // When the carousel slides, auto update the text
        $('#myCarousel').on('slid', function (e) {
                var id = $('.item.active').data('slide-number');
                $('#carousel-text').html($('#slide-content-'+id).html());
        });
});
</script>