config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :addresses, only: [:create, :destroy, :update, :edit, :new]
  resources :bank_accounts, only: [:create, :destroy, :update, :edit, :new]
  resources :pictures

  devise_for :administrators
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks" }

  authenticated :admin do
    root to: 'users#index'
  end

  authenticated :user do
    root to: 'listings#index'
  end
  
  resources :listings do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :users do
    resources :comments, only: [:new, :create, :destroy]
  end

=begin
  # Usuarios admin Ya está hecho
  get "admins/users/new" => 'users#new', as: 'add_user_admin'
  post "admins/users/new" => 'users#create', as: 'login_admin_user'
  get "admins/users/:id/edit" => "users#edit", as: "edit_user_adm"
  patch "admins/users/:id" => 'users#update', as: 'edit_user_admin'
  delete "admins/users/:id" => 'users#destroy', as: 'destroy_user_admin'
  get "admins/users" => 'users#index', as: 'list_user_admin'

  #subjects admin Ya está hecho
  get "admins/subjects" => 'subjects#index', as: 'subjects'
  post "admins/subjects" =>  'subjects#create'
  get "admins/subjects/new" => "subjects#new", as:'new_subject'                             
  get "admins/subjects/:id/edit" => "subjects#edit", as: "edit_subject" 
  get "admins/subjects/:id" => "subjects#show", as:"subject"
  patch "admins/subjects/:id" => "subjects#update"
  put "admins/subjects/:id" => "subjects#update"
  delete "admins/subjects/:id" => "subjects#destroy"

  #categorias admin Ya está hecho
  get "admins/categories" => 'categories#index', as: 'categories'
  post "admins/categories" =>  'categories#create'
  get "admins/categories/new" => "categories#new", as:'new_category'                             
  get "admins/categories/:id/edit" => "categories#edit", as: "edit_category" 
  get "admins/categories/:id" => "categories#show", as:"category"
  patch "admins/categories/:id" => "categories#update"
  put "admins/categories/:id" => "categories#update"
  delete "admins/categories/:id" => "categories#destroy"

  #artwork admin
  get "admins/artworks" => 'listings#index_admin', as: 'artworks_list'
  post "admins/artworks/new" =>  'listings#create_admin'
  get "admins/artworks/new" => "listings#new_admin", as:'new_listing_admin'                             
  get "admins/artworks/:id/edit" => "listings#edit_admin", as: "edit_listing_admin" 
  patch "admins/artworks/:id" => "listings#update_admin", as: "update_listing_admin"
  put "admins/artworks/:id" => "listings#update_admin"
  delete "admins/artworks/:id" => "listings#destroy_admin", as:"destroy_listing_admin"

  #addresses admin
  get "admins/addresses" => 'addresses#index_admin', as: 'addresses_list'
  post "admins/addresses/new" =>  'addresses#create_admin', as:'create_address_admin'
  get "admins/addresses/new" => "addresses#new_admin", as:'new_address_admin'                             
  get "admins/addresses/:id/edit" => "addresses#edit_admin", as: "edit_address_admin" 
  patch "admins/addresses/:id" => "addresses#update_admin", as: "update_address_admin"
  put "admins/addresses/:id" => "addresses#update_admin"
  delete "admins/addresses/:id" => "addresses#destroy_admin", as:"destroy_address_admin"

  #bank accounts_admin
  get "admins/bank_accounts" => 'bank_accounts#index_admin', as: 'bank_accounts_list'
  post "admins/bank_accounts/new" =>  'bank_accounts#create_admin', as: 'create_bank_account_admin'
  get "admins/bank_accounts/new" => "bank_accounts#new_admin", as:'new_bank_account_admin'                             
  get "admins/bank_accounts/:id/edit" => "bank_accounts#edit_admin", as: "edit_bank_account_admin" 
  patch "admins/bank_accounts/:id" => "bank_accounts#update_admin", as: "update_bank_account_admin"
  put "admins/bank_accounts/:id" => "bank_accounts#update_admin"
  delete "admins/bank_accounts/:id" => "bank_accounts#destroy_admin", as:"destroy_bank_account_admin"
=end

  match '/admin/administrators' => redirect('/admin/users'), via: [:get]
  match '/admin/signin' =>redirect('administrators/sign_in'), via: [:get]
  get "/vacio" => "templates#vacio", as: "edit_admin_administrator"

  Tolaria.draw_routes(self)

  #AJAX
  get "/fetch_listings" => 'listings#from_category', as: 'fetch_listings'
  get "/fetch_subjects" => 'listings#subjects', as: 'fetch_subjects'
  get "/fetch_comments_listing" => 'listings#comments', as: 'fetch_comments_listing'
  get "/fetch_listings_user" => 'users#listings', as: 'fetch_listings_user'
  get "/fetch_comments_user" => 'users#comments', as: 'fetch_comments_user'

  get '/pages/styles'
  get '/pages/appreciation'
  get '/pages/exhibition'
  get '/pages/artist'
  get '/pages/top_artist'
  get '/pages/museums'
  get '/pages/art_appreciation'
  get '/pages/about_us'
  get '/contact', to: 'messages#new', as: 'pages_contact'
  get "/curated" => 'listings#curated', as:"listings_curated"
  get '/listings' => 'listings#index', defaults: { format: 'js' }
  get "/elearning" => 'pages#elearning', as:"pages_elearning"
  get "/about" => 'pages#about', as:"pages_about"
  get '/seller' => "listings#seller"
  get '/sales' => "orders#sales"
  get '/purchases' => "orders#purchases"
  get "/search" => "pages#search", as:"search"
  get '/:nick' => 'users#show', as:"user_profile"
  get "/add/:listing_id", as: :add_to_cart, to: "in_shopping_carts#create"
  get "/price/:range" => 'listings#from_price', as:'range_price'
  get "/pages_category/:category/" => 'pages#pages_category', as: 'pages_category'
  get "/pages_subject/:subject/" => 'pages#pages_subject', as: 'pages_subject'
  get "/bysubject/:subject" => 'listings#from_subject', as: 'from_subject'

  post '/contact', to: 'messages#create'

  root 'listings#index'
  
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :listings, dependent: :destroy
	mount_uploader :image, PictureArtUploader

	manage_with_tolaria using: {
		icon: "newspaper-o",
		category: "Content administration",
		priority: 3,
		permit_params: [
			:name,
			:image
		]
	}
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all.order(:name)
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :image)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(subject) do |f| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<%= render 'shared_admin/menu' %>
<div class = "col-md-10 text-center">
<h4>Subjects</h4>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th colspan="3"></th>
  </tr>

  <% @subjects.each do |subject| %>
    <tr>
      <% if subject.image.present?%>
        <td class="center"><%= image_tag subject.image.url(:thumb) %></td>
      <% else %>
        <td class="center">No image</td>
      <% end %>
      <td class="center"><%= subject.name %></td>
      <td class="center"><%= link_to 'Show', subject %></td>
      <td class="center"><%= link_to 'Edit', edit_subject_path(subject) %></td>
      <td class="center"><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>
</div>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @subject.image.url(:large) %>
    </div>
  </div>
  <div class="col-md-6">

  <h3><%= @subject.name %></h3>

  </div>
</div>
<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>