config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :addresses, only: [:create, :destroy, :update, :edit, :new]
  resources :bank_accounts, only: [:create, :destroy, :update, :edit, :new]
  resources :pictures

  devise_for :administrators
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks" }

  authenticated :admin do
    root to: 'users#index'
  end

  authenticated :user do
    root to: 'listings#index'
  end
  
  resources :listings do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :users do
    resources :comments, only: [:new, :create, :destroy]
  end

=begin
  # Usuarios admin Ya está hecho
  get "admins/users/new" => 'users#new', as: 'add_user_admin'
  post "admins/users/new" => 'users#create', as: 'login_admin_user'
  get "admins/users/:id/edit" => "users#edit", as: "edit_user_adm"
  patch "admins/users/:id" => 'users#update', as: 'edit_user_admin'
  delete "admins/users/:id" => 'users#destroy', as: 'destroy_user_admin'
  get "admins/users" => 'users#index', as: 'list_user_admin'

  #subjects admin Ya está hecho
  get "admins/subjects" => 'subjects#index', as: 'subjects'
  post "admins/subjects" =>  'subjects#create'
  get "admins/subjects/new" => "subjects#new", as:'new_subject'                             
  get "admins/subjects/:id/edit" => "subjects#edit", as: "edit_subject" 
  get "admins/subjects/:id" => "subjects#show", as:"subject"
  patch "admins/subjects/:id" => "subjects#update"
  put "admins/subjects/:id" => "subjects#update"
  delete "admins/subjects/:id" => "subjects#destroy"

  #categorias admin Ya está hecho
  get "admins/categories" => 'categories#index', as: 'categories'
  post "admins/categories" =>  'categories#create'
  get "admins/categories/new" => "categories#new", as:'new_category'                             
  get "admins/categories/:id/edit" => "categories#edit", as: "edit_category" 
  get "admins/categories/:id" => "categories#show", as:"category"
  patch "admins/categories/:id" => "categories#update"
  put "admins/categories/:id" => "categories#update"
  delete "admins/categories/:id" => "categories#destroy"

  #artwork admin
  get "admins/artworks" => 'listings#index_admin', as: 'artworks_list'
  post "admins/artworks/new" =>  'listings#create_admin'
  get "admins/artworks/new" => "listings#new_admin", as:'new_listing_admin'                             
  get "admins/artworks/:id/edit" => "listings#edit_admin", as: "edit_listing_admin" 
  patch "admins/artworks/:id" => "listings#update_admin", as: "update_listing_admin"
  put "admins/artworks/:id" => "listings#update_admin"
  delete "admins/artworks/:id" => "listings#destroy_admin", as:"destroy_listing_admin"

  #addresses admin
  get "admins/addresses" => 'addresses#index_admin', as: 'addresses_list'
  post "admins/addresses/new" =>  'addresses#create_admin', as:'create_address_admin'
  get "admins/addresses/new" => "addresses#new_admin", as:'new_address_admin'                             
  get "admins/addresses/:id/edit" => "addresses#edit_admin", as: "edit_address_admin" 
  patch "admins/addresses/:id" => "addresses#update_admin", as: "update_address_admin"
  put "admins/addresses/:id" => "addresses#update_admin"
  delete "admins/addresses/:id" => "addresses#destroy_admin", as:"destroy_address_admin"

  #bank accounts_admin
  get "admins/bank_accounts" => 'bank_accounts#index_admin', as: 'bank_accounts_list'
  post "admins/bank_accounts/new" =>  'bank_accounts#create_admin', as: 'create_bank_account_admin'
  get "admins/bank_accounts/new" => "bank_accounts#new_admin", as:'new_bank_account_admin'                             
  get "admins/bank_accounts/:id/edit" => "bank_accounts#edit_admin", as: "edit_bank_account_admin" 
  patch "admins/bank_accounts/:id" => "bank_accounts#update_admin", as: "update_bank_account_admin"
  put "admins/bank_accounts/:id" => "bank_accounts#update_admin"
  delete "admins/bank_accounts/:id" => "bank_accounts#destroy_admin", as:"destroy_bank_account_admin"
=end

  match '/admin/administrators' => redirect('/admin/users'), via: [:get]
  match '/admin/signin' =>redirect('administrators/sign_in'), via: [:get]
  get "/vacio" => "templates#vacio", as: "edit_admin_administrator"

  Tolaria.draw_routes(self)

  #AJAX
  get "/fetch_listings" => 'listings#from_category', as: 'fetch_listings'
  get "/fetch_subjects" => 'listings#subjects', as: 'fetch_subjects'
  get "/fetch_comments_listing" => 'listings#comments', as: 'fetch_comments_listing'
  get "/fetch_listings_user" => 'users#listings', as: 'fetch_listings_user'
  get "/fetch_comments_user" => 'users#comments', as: 'fetch_comments_user'

  get '/pages/styles'
  get '/pages/appreciation'
  get '/pages/exhibition'
  get '/pages/artist'
  get '/pages/top_artist'
  get '/pages/museums'
  get '/pages/art_appreciation'
  get '/pages/about_us'
  get '/contact', to: 'messages#new', as: 'pages_contact'
  get "/curated" => 'listings#curated', as:"listings_curated"
  get '/listings' => 'listings#index', defaults: { format: 'js' }
  get "/elearning" => 'pages#elearning', as:"pages_elearning"
  get "/about" => 'pages#about', as:"pages_about"
  get '/seller' => "listings#seller"
  get '/sales' => "orders#sales"
  get '/purchases' => "orders#purchases"
  get "/search" => "pages#search", as:"search"
  get '/:nick' => 'users#show', as:"user_profile"
  get "/add/:listing_id", as: :add_to_cart, to: "in_shopping_carts#create"
  get "/price/:range" => 'listings#from_price', as:'range_price'
  get "/pages_category/:category/" => 'pages#pages_category', as: 'pages_category'
  get "/pages_subject/:subject/" => 'pages#pages_subject', as: 'pages_subject'
  get "/bysubject/:subject" => 'listings#from_subject', as: 'from_subject'

  post '/contact', to: 'messages#create'

  root 'listings#index'
  
end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base

  validates :bank, presence: true
  validates :number, presence: true
  validates :country, presence: true

  belongs_to :user

	manage_with_tolaria using: {
	icon: "money",
	category: "User administration",
	priority: 3,
		permit_params: [
			:bank,
			:number,
			:country,
			:user_id
		]
	}
	
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]


  # GET /bank_accounts/new
  def new
    @bank_account = current_user.bank_accounts.new
  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  # POST /bank_accounts.json
  def create
    @bank_account = current_user.bank_accounts.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to edit_user_registration_url, notice: 'Bank account was successfully created.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1
  # PATCH/PUT /bank_accounts/1.json
  def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to edit_user_registration_url, notice: 'Bank account was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1
  # DELETE /bank_accounts/1.json
  def destroy
    @bank_account.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_registration_url, notice: 'Bank account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = current_user.bank_accounts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:bank, :number, :country)
    end
    
end

app/helpers/bank_account_helper.rb
module BankAccountHelper
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/_form.html.erb
<%= form_for(bank_account) do |f| %>
  <% if bank_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank_account.errors.count, "error") %> prohibited this bank_account from being saved:</h2>

      <ul>
      <% bank_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :bank %>
    <%= f.text_field :bank, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :number %>
    <%= f.text_field :number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bank_accounts/edit.html.erb
<h1>Editing Bank Account</h1>

<%= render 'form', bank_account: @bank_account %>

<%= link_to 'Show', @bank_account %> |
<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/edit_admin.html.erb
<%= form_for(@bank_account, :url => update_bank_account_admin_path(@bank_account)) do |f| %>
  <% if @bank_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank_account.errors.count, "error") %> prohibited this bank_account from being saved:</h2>

      <ul>
      <% @bank_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id %><br>
    <% @users = User.all %>
    <%= f.select :user_id, options_for_select(@users.map{ |s| [s.email, s.id] }, selected_key = @bank_account.user_id),{ :include_blank => false }, { :class => 'btn btn-primary' } %>
  </div>

  <div class="form-group">
    <%= f.label :bank %>
    <%= f.text_field :bank, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :number %>
    <%= f.text_field :number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bank_accounts/index_admin.html.erb
<%= render 'shared_admin/menu' %>
<div class = "col-md-10 text-center">
  <h4>Bank accounts</h4>

  <table class="table table-striped table-bordered">
    <tr>
      <th class="center">Bank</th>
      <th class="center">Number</th>
      <th class="center">Country</th>
      <th class="center">User</th>
      <th colspan="2"></th>
    </tr>

    <% @bank_accounts.each do |bank| %>
      <tr>
        <td class="center"><%= bank.bank %></td>
        <td class="center"><%= bank.number %></td>
        <td class="center"><%= bank.country %></td>
        <% user = User.find(bank.user_id)%>
        <td class="center"><%= user.first_name + ' ' + user.last_name %> <br> <%= user.email%></td>
        <td class="center"><%= link_to 'Edit', edit_bank_account_admin_path(bank) %></td>
        <td class="center"><%= link_to 'Destroy', destroy_bank_account_admin_path(bank), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <br>

  <%= link_to 'New bank account', new_bank_account_admin_path %>
</div>

app/views/bank_accounts/new.html.erb
<h1>New Bank Account</h1>

<%= render 'form', bank_account: @bank_account %>

<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/new_admin.html.erb
<%= form_for(@bank_account, :url => create_bank_account_admin_path(@bank_account)) do |f| %>
  <% if @bank_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank_account.errors.count, "error") %> prohibited this bank_account from being saved:</h2>

      <ul>
      <% @bank_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id %><br>
    <% @users = User.all %>
    <%= f.select :user_id, options_for_select(@users.map{ |s| [s.email, s.id] }, selected_key = @bank_account.user_id),{ :include_blank => false }, { :class => 'btn btn-primary' } %>
  </div>

  <div class="form-group">
    <%= f.label :bank %>
    <%= f.text_field :bank, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :number %>
    <%= f.text_field :number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>